module.exports = [
  {
    id: 1,
    name: '布偶猫',
    species: '长毛猫',
    emoji: '🐱',
    rarity: 'rare',
    badge: '甜梦陪伴',
    theme: '#EEF6FF',
    accent: '#72A9FF',
    quote: '像把课后的成就感揉成一团柔软云朵。',
    vibe: '每次完成任务，它都会把掌声悄悄留在学生身边。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/buomao/1200000229.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/buomao/1200000229.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/buomao/12000002290.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/buomao/12000002298.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/buomao/12000002306.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/buomao/12000002314.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/buomao/12000002322.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/buomao/12000002330.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/buomao/12000002338.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/buomao/12000002346.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/buomao/12000002354.jpg'
    ]
  },
  {
    id: 2,
    name: '柯基',
    species: '短腿牧犬',
    emoji: '🐶',
    rarity: 'common',
    badge: '快乐冲刺',
    theme: '#FFF6E8',
    accent: '#FF9B54',
    quote: '短腿也能全速冲榜，是班里的快乐加速器。',
    vibe: '一被夸奖就会摇着尾巴陪学生继续闯关。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/keji/10001.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/keji/10001.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/keji/10002.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/keji/10003.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/keji/10004.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/keji/10005.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/keji/10006.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/keji/10007.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/keji/10008.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/keji/10009.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/keji/10010.jpg'
    ]
  },
  {
    id: 3,
    name: '垂耳兔',
    species: '垂耳兔',
    emoji: '🐰',
    rarity: 'common',
    badge: '柔软陪伴',
    theme: '#FFF2F8',
    accent: '#F58AB2',
    quote: '软软地陪着孩子，把每个任务都做得很认真。',
    vibe: '安静的时候最会给人安全感，适合小班教学的温柔氛围。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/chuietu/12000000255.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/chuietu/12000000255.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/chuietu/12000000256.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/chuietu/12000000264.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/chuietu/12000000272.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/chuietu/12000000280.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/chuietu/12000000288.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/chuietu/12000000296.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/chuietu/12000000304.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/chuietu/12000000312.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/chuietu/12000000320.jpg'
    ]
  },
  {
    id: 4,
    name: '金渐层',
    species: '金渐层',
    emoji: '🐈',
    rarity: 'rare',
    badge: '金色高光',
    theme: '#FFF7E2',
    accent: '#F6B341',
    quote: '像一枚金色奖励章，特别适合高光时刻出场。',
    vibe: '每次升级都像点亮一层金色小勋章，仪式感很强。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/glodcat/100000231.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/glodcat/100000231.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/glodcat/10500000030.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/glodcat/10500000038.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/glodcat/10500000046.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/glodcat/10500000054.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/glodcat/10500000062.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/glodcat/10500000070.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/glodcat/10500000078.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/glodcat/10500000086.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/glodcat/10500000094.jpg'
    ]
  },
  {
    id: 5,
    name: '英短蓝猫',
    species: '英短蓝猫',
    emoji: '🐱',
    rarity: 'rare',
    badge: '冷静守护',
    theme: '#EEF4FF',
    accent: '#6D8DFF',
    quote: '表面有点傲娇，其实超会守护课堂节奏。',
    vibe: '适合稳稳发力、慢慢变强的学生，越看越有气质。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yingduan/1200000151.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yingduan/1200000151.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yingduan/12000001951.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yingduan/12000001959.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yingduan/12000001967.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yingduan/12000001975.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yingduan/12000001983.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yingduan/12000001991.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yingduan/12000001999.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yingduan/12000002007.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yingduan/12000002015.jpg'
    ]
  },
  {
    id: 6,
    name: '柴犬',
    species: '柴犬',
    emoji: '🐕',
    rarity: 'common',
    badge: '元气担当',
    theme: '#FFF3E5',
    accent: '#FF8A3D',
    quote: '永远元气在线，最会把课堂气氛带热。',
    vibe: '越是被表扬，越能激发下一次冲刺欲，特别适合课堂鼓励。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/caiquan/12000000030.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/caiquan/12000000030.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/caiquan/12000000038.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/caiquan/12000000046.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/caiquan/12000000054.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/caiquan/12000000062.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/caiquan/12000000070.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/caiquan/12000000078.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/caiquan/12000000086.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/caiquan/12000000094.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/caiquan/CQ.jpg'
    ]
  },
  {
    id: 7,
    name: '布丁仓鼠',
    species: '布丁仓鼠',
    emoji: '🐹',
    rarity: 'common',
    badge: '治愈满分',
    theme: '#FFF8E8',
    accent: '#F4C15D',
    quote: '小小一只，却能把治愈值和仪式感一起拉满。',
    vibe: '每次露脸都像打开一颗甜甜的布丁盲盒，很讨孩子喜欢。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/budding/10001.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/budding/10001.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/budding/10002.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/budding/10003.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/budding/10004.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/budding/10005.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/budding/10006.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/budding/10007.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/budding/10008.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/budding/10009.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/budding/10010.jpg'
    ]
  },
  {
    id: 8,
    name: '龙猫',
    species: '龙猫',
    emoji: '🐭',
    rarity: 'rare',
    badge: '软萌陪伴',
    theme: '#F1F5F9',
    accent: '#94A3B8',
    quote: '软乎乎的一团，最受小班学员欢迎。',
    vibe: '它的成长像陪伴一样慢慢积累，适合长期打磨学习习惯。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/longmao/1200000934.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/longmao/1200000934.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/longmao/12000000934.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/longmao/12000000942.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/longmao/12000000950.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/longmao/12000000958.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/longmao/12000000966.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/longmao/12000000974.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/longmao/12000000982.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/longmao/12000000990.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/longmao/12000000998.jpg'
    ]
  },
  {
    id: 9,
    name: '比熊',
    species: '比熊',
    emoji: '🐩',
    rarity: 'rare',
    badge: '云朵主角',
    theme: '#F8FAFC',
    accent: '#8BC4FF',
    quote: '像会发光的小云朵，适合温柔又闪亮的学生。',
    vibe: '每次亮相都自带“今天表现超棒”的氛围，非常有情绪价值。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bixiong/100000363.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bixiong/100000363.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bixiong/10500000482.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bixiong/10500000490.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bixiong/10500000498.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bixiong/10500000506.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bixiong/10500000514.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bixiong/10500000522.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bixiong/10500000530.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bixiong/10500000538.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bixiong/10500000546.jpg'
    ]
  },
  {
    id: 10,
    name: '边牧',
    species: '边境牧羊犬',
    emoji: '🐕',
    rarity: 'epic',
    badge: '聪明执行',
    theme: '#F4F7FF',
    accent: '#4F6DFF',
    quote: '聪明、灵敏、执行力强，是冲榜型搭档。',
    vibe: '适合那种一进入状态就停不下来的学生，特别有“主角队友”气质。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bianmu/100000396.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bianmu/100000396.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bianmu/10500000821.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bianmu/10500000829.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bianmu/10500000837.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bianmu/10500000845.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bianmu/10500000853.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bianmu/10500000861.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bianmu/10500000869.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bianmu/10500000877.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/bianmu/10500000885.jpg'
    ]
  },
  {
    id: 11,
    name: '雪豹',
    species: '雪豹',
    emoji: '🐆',
    rarity: 'epic',
    badge: '竞技觉醒',
    theme: '#F2F7FF',
    accent: '#7C8CFF',
    quote: '带一点竞技感，适合未来班级战斗玩法铺垫。',
    vibe: '当课堂进入冲刺阶段，它会显得格外有压迫感和存在感。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/xuebao/01.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/xuebao/01.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/xuebao/02.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/xuebao/03.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/xuebao/04.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/xuebao/05.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/xuebao/07.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/xuebao/8.1.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/xuebao/8.2.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/xuebao/09.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/xuebao/x.jpg'
    ]
  },
  {
    id: 12,
    name: '白泽',
    species: '神兽',
    emoji: '✨',
    rarity: 'legendary',
    badge: '神话压轴',
    theme: '#FFF8EA',
    accent: '#D4A62A',
    quote: '从蛋壳亮相的那一刻，就有神兽登场的仪式感。',
    vibe: '非常适合做班级压轴展示和荣誉奖励，学生会立刻觉得“这次真的不一样”。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/baize/01.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/baize/01.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/baize/02.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/baize/03.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/baize/04.1.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/baize/05.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/baize/06.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/baize/08.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/baize/09.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/baize/10.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/baize/11.jpg'
    ]
  },
  {
    id: 13,
    name: '应龙',
    species: '神龙',
    emoji: '🐉',
    rarity: 'legendary',
    badge: '冠军终章',
    theme: '#EFFAF8',
    accent: '#13A39B',
    quote: '成长后像冠军皮肤，特别适合全班注目的时刻。',
    vibe: '它的终阶形态会让学生真正感到“我练出来了”，非常适合进化仪式。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yinglong/01.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yinglong/01.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yinglong/02.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yinglong/03.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yinglong/04.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yinglong/05.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yinglong/06.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yinglong/07.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yinglong/08.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yinglong/09.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/yinglong/10.jpg'
    ]
  },
  {
    id: 14,
    name: '火龙',
    species: '神龙',
    emoji: '🐲',
    rarity: 'legendary',
    badge: '战意点燃',
    theme: '#FFF1EE',
    accent: '#F95D4E',
    quote: '终阶形态非常燃，为后续战斗玩法预留了想象空间。',
    vibe: '一旦进化成功，现场的情绪会被瞬间点燃，非常适合作为压轴宠物。',
    image: 'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/huolong/01.jpg',
    evolutionStages: [
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/huolong/01.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/huolong/02.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/huolong/03.1.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/huolong/03.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/huolong/04.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/huolong/05.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/huolong/06.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/huolong/08.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/huolong/09.jpg',
      'https://brvjqiusgeqeyfadfwga.supabase.co/storage/v1/object/public/cwk/huolong/10.jpg'
    ]
  }
];
